version: '2'
services:
  # Aldea
  aldea-database:
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: aldea_production
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: $ALDEA_DATABASE_USER
      MYSQL_PASSWORD: $ALDEA_DATABASE_PASSWORD
    volumes:
      - aldea:/var/lib/mysql
    networks:
      - aldea
      - dios-aldea
  aldea-application:
    image: registry.neec.xyz/neeco/aldea-application:latest
    environment:
      ALDEA_PORT: 3000
      ALDEA_DATABASE_HOST: aldea-database
      ALDEA_DATABASE_USER:
      ALDEA_DATABASE_PASSWORD:
      ALDEA_SECRET_KEY_BASE:
      CUENTA_URL: http://cuenta-application:4000
      STATIC_URL: https://static.neec.ooo
    depends_on:
      - aldea-database
    volumes:
      - public:/app/uploads/
    networks:
      - aldea
      - aldea-cuenta
      - kong-aldea

  # Cadena
  cadena-database:
    image: neo4j:3.0.7
    environment:
      NEO4J_AUTH: none
    volumes:
      - cadena:/data
    networks:
      - cadena
  cadena-application:
    image: registry.neec.xyz/neeco/cadena-application:latest
    environment:
      CADENA_PORT: 3000
      CADENA_DATABASE_URL: http://cadena-database:7474
      CADENA_SECRET_KEY_BASE:
      CUENTA_URL: http://cuenta-application:4000/
      CAJA_URL: http://caja-application:9000/
    depends_on:
      - cadena-database
    networks:
      - cadena
      - cadena-cuenta
      - kong-cadena

  # Cuenta
  cuenta-database:
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: cuenta_prod
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: $CUENTA_DATABASE_USER
      MYSQL_PASSWORD: $CUENTA_DATABASE_PASSWORD
    ports: # TODO: ダミーデータ挿入のために開けている。頃合い見て閉じる
      - "13306:3306"
    volumes:
      - cuenta:/var/lib/mysql
    networks:
      - cuenta
      - dios-cuenta
  cuenta-application:
    image: registry.neec.xyz/neeco/cuenta-application:latest
    environment:
      CUENTA_PORT: 4000
      CUENTA_DATABASE_HOST: cuenta-database
      CUENTA_DATABASE_USER:
      CUENTA_DATABASE_PASSWORD:
      KONG_URL: http://kong-application:8001
      STATIC_URL:
    depends_on:
      - cuenta-database
    volumes:
      - public:/app/uploads/
    networks:
      - cuenta
      - aldea-cuenta
      - cadena-cuenta
      - kong-cuenta

  # Dios
  dios-database:
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: dios_production
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: $DIOS_DATABASE_USER
      MYSQL_PASSWORD: $DIOS_DATABASE_PASSWORD
    volumes:
      - dios:/var/lib/mysql
    networks:
      - dios
  dios-application:
    image: registry.neec.xyz/neeco/dios-application:latest
    environment:
      DIOS_PORT: 3000
      DIOS_DATABASE_HOST: dios-database
      DIOS_DATABASE_USER:
      DIOS_DATABASE_PASSWORD:
      DIOS_SECRET_KEY_BASE:
      KONG_URL: http://kong-application:8001
      CUENTA_DATABASE_HOST: cuenta-database
      CUENTA_DATABASE_USER:
      CUENTA_DATABASE_PASSWORD:
      ALDEA_DATABASE_HOST: aldea-database
      ALDEA_DATABASE_USER:
      ALDEA_DATABASE_PASSWORD:
    depends_on:
      - dios-database
    networks:
      - dios
      - puerta-dios
      - dios-aldea
      - dios-cuenta
      - dios-kong

  # Kong
  kong-database:
    image: postgres:9.4
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    volumes:
      - kong:/var/lib/postgresql/data
    networks:
      - kong
  kong-application:
    image: registry.neec.xyz/neeco/kong-application:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
    depends_on:
      - kong-database
    networks:
      - kong
      - puerta-kong
      - kong-aldea
      - kong-cadena
      - kong-cuenta
      - dios-kong

  # Puerta
  puerta:
    image: registry.neec.xyz/neeco/puerta:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.htpasswd:/etc/h2o/.htpasswd:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - public:/public/:ro
    networks:
      - puerta
      - puerta-web
      - puerta-kong
      - puerta-dios

volumes:
  aldea:
    external:
      name: neeco_aldea
  cadena:
    external:
      name: neeco_cadena
  cuenta:
    external:
      name: neeco_cuenta
  dios:
    external:
      name: neeco_dios
  kong:
    external:
      name: neeco_kong
  public:
    external:
      name: neeco_public

networks:
  aldea:
    external:
      name: neeco_aldea
  cuenta:
    external:
      name: neeco_cuenta
  cadena:
    external:
      name: neeco_cadena
  dios:
    external:
      name: neeco_dios
  kong:
    external:
      name: neeco_kong
  puerta:
    external:
      name: neeco_puerta
  puerta-web:
    external:
      name: neeco_puerta-web
  puerta-kong:
    external:
      name: neeco_puerta-kong
  puerta-dios:
    external:
      name: neeco_puerta-dios
  kong-aldea:
    external:
      name: neeco_kong-aldea
  kong-cadena:
    external:
      name: neeco_kong-cadena
  kong-cuenta:
    external:
      name: neeco_kong-cuenta
  dios-aldea:
    external:
      name: neeco_dios-aldea
  dios-cuenta:
    external:
      name: neeco_dios-cuenta
  dios-kong:
    external:
      name: neeco_dios-kong
  aldea-cuenta:
    external:
      name: neeco_aldea-cuenta
  cadena-cuenta:
    external:
      name: neeco_cadena-cuenta
