version: '2'
services:
  # Kong
  kong-datastore:
    extends:
      file: docker-kong.yml
      service: datastore
  kong-database:
    extends:
      file: docker-kong.yml
      service: database
    volumes_from:
      - kong-datastore
    networks:
      - kong
  kong-application:
    extends:
      file: docker-kong.yml
      service: application
    depends_on:
      - kong-database
    volumes_from:
      - kong-datastore
    networks:
      - kong-cuenta
      - kong

  # Cuenta
  cuenta-datastore:
    extends:
      file: docker-cuenta.yml
      service: datastore
  cuenta-database:
    extends:
      file: docker-cuenta.yml
      service: database
    volumes_from:
      - cuenta-datastore
    networks:
      - cuenta
  cuenta-application:
    extends:
      file: docker-cuenta.yml
      service: application
    depends_on:
      - cuenta-database
    volumes_from:
      - cuenta-datastore
    networks:
      - kong-cuenta
      - cuenta

networks:
  kong-cuenta:
    driver: bridge
  kong:
    driver: bridge
  cuenta:
    driver: bridge
