version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - /var/lib/mysql
      - /app/log
  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
  application:
    image: aldea-application
    environment:
      - ALDEA_PORT=3000
      - ALDEA_DATABASE_HOST=aldea-database
      - ALDEA_DATABASE_USER=root
      - ALDEA_DATABASE_PASSWORD=root
      - ALDEA_SECRET_KEY_BASE=1f0bef8714009078799cf781b489f5012c625a12dc4478388634af4b784b72c5bd1e3f2630a361af351cfaf5bf84559f818b2796b9fcbc331cfa404a3805cb6f
