version: '2'
services:
  # Aldea
  aldea-database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - aldea:/var/lib/mysql
    networks:
      - aldea
      - dios-aldea
  aldea-application:
    image: aldea-application
    environment:
      - ALDEA_PORT=3000
      - ALDEA_DATABASE_HOST=aldea-database
      - ALDEA_DATABASE_USER=root
      - ALDEA_DATABASE_PASSWORD=root
      - ALDEA_SECRET_KEY_BASE=1f0bef8714009078799cf781b489f5012c625a12dc4478388634af4b784b72c5bd1e3f2630a361af351cfaf5bf84559f818b2796b9fcbc331cfa404a3805cb6f
    depends_on:
      - aldea-database
    networks:
      - aldea
      - aldea-cuenta
      - kong-aldea

  # Cuenta
  cuenta-database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports: # TODO: ダミーデータ挿入のために開けている。頃合い見て閉じる
      - "13306:3306"
    volumes:
      - cuenta:/var/lib/mysql
    networks:
      - cuenta
      - dios-cuenta
  cuenta-application:
    image: cuenta-application
    environment:
      - CUENTA_PORT=4000
      - CUENTA_DATABASE_HOST=cuenta-database
      - CUENTA_DATABASE_USER=root
      - CUENTA_DATABASE_PASSWORD=root
      - CUENTA_KONG_URL=http://kong-application:8001
      - CUENTA_IMAGE_URL=http://localhost
    depends_on:
      - cuenta-database
    volumes:
      - public:/app/uploads/
    networks:
      - cuenta
      - aldea-cuenta
      - kong-cuenta

  # Dios
  dios-database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dios:/var/lib/mysql
    networks:
      - dios
  dios-application:
    image: dios-application
    environment:
      - DIOS_PORT=3000
      - DIOS_DATABASE_HOST=dios-database
      - DIOS_DATABASE_USER=root
      - DIOS_DATABASE_PASSWORD=root
      - DIOS_SECRET_KEY_BASE=1f0bef8714009078799cf781b489f5012c625a12dc4478388634af4b784b72c5bd1e3f2630a361af351cfaf5bf84559f818b2796b9fcbc331cfa404a3805cb6f
      - DIOS_KONG_URL=http://kong-application:8001
      - CUENTA_DATABASE_HOST=cuenta-database
      - CUENTA_DATABASE_USER=root
      - CUENTA_DATABASE_PASSWORD=root
      - ALDEA_DATABASE_HOST=aldea-database
      - ALDEA_DATABASE_USER=root
      - ALDEA_DATABASE_PASSWORD=root
    ports:
      - "3000:3000"
    depends_on:
      - dios-database
    networks:
      - dios
      - dios-aldea
      - dios-cuenta
      - dios-kong

  # Kong
  kong-database:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    volumes:
      - kong:/var/lib/postgresql/data
    networks:
      - kong
  kong-application:
    image: kong-application
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    ports:
      - "8000:8000" # public api http
      - "80:80"     # pubic image
      - "8001:8001" # admin api
      - "8443:8443" # public api https
    depends_on:
      - kong-database
    volumes:
      - public:/public/:ro
    networks:
      - kong
      - kong-aldea
      - kong-cuenta
      - dios-kong

volumes:
  aldea:
    external:
      name: neeco_aldea
  cuenta:
    external:
      name: neeco_cuenta
  dios:
    external:
      name: neeco_dios
  kong:
    external:
      name: neeco_kong
  public:
    external:
      name: neeco_public

networks:
  aldea:
    external:
      name: neeco_aldea
  cuenta:
    external:
      name: neeco_cuenta
  dios:
    external:
      name: neeco_dios
  kong:
    external:
      name: neeco_kong
  kong-aldea:
    external:
      name: neeco_kong-aldea
  kong-cuenta:
    external:
      name: neeco_kong-cuenta
  dios-aldea:
    external:
      name: neeco_dios-aldea
  dios-cuenta:
    external:
      name: neeco_dios-cuenta
  dios-kong:
    external:
      name: neeco_dios-kong
  aldea-cuenta:
    external:
      name: neeco_aldea-cuenta
