version: '2'
services:
  # Aldea
  aldea-database:
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: aldea_production
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: $ALDEA_DATABASE_USER
      MYSQL_PASSWORD: $ALDEA_DATABASE_PASSWORD
    volumes:
      - aldea:/var/lib/mysql
    networks:
      - aldea
      - dios-aldea
  aldea-application:
    image: registry.neec.xyz/neeco/aldea-application:latest
    environment:
      RAILS_LOG_TO_STDOUT: 'true'
      ALDEA_PORT: 3000
      ALDEA_DATABASE_HOST: aldea-database
      ALDEA_DATABASE_USER:
      ALDEA_DATABASE_PASSWORD:
      ALDEA_SECRET_KEY_BASE:
      CUENTA_URL: http://cuenta-application:4000/
      IMAGEN_URL: http://imagen-application:8000/
      STATIC_IMAGE_URL:
    depends_on:
      - aldea-database
    networks:
      - aldea
      - aldea-cuenta
      - aldea-imagen
      - kong-aldea

  # Cadena
  cadena-database:
    image: neo4j:3.0.7
    environment:
      NEO4J_AUTH: none
    volumes:
      - cadena:/data
    networks:
      - cadena
  cadena-application:
    image: registry.neec.xyz/neeco/cadena-application:latest
    environment:
      RAILS_LOG_TO_STDOUT: 'true'
      CADENA_PORT: 3000
      CADENA_DATABASE_URL: http://cadena-database:7474/
      CADENA_SECRET_KEY_BASE:
      CAJA_URL: http://caja-application:9000/
      CUENTA_URL: http://cuenta-application:4000/
      IMAGEN_URL: http://imagen-application:8000/
      STATIC_IMAGE_URL:
    depends_on:
      - cadena-database
    networks:
      - cadena
      - cadena-cuenta
      - cadena-imagen
      - caja-cadena
      - kong-cadena

  # Caja
  caja-database:
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: caja_production
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: $CAJA_DATABASE_USER
      MYSQL_PASSWORD: $CAJA_DATABASE_PASSWORD
    volumes:
      - caja:/var/lib/mysql
    networks:
      - caja
      - dios-caja
  caja-application:
    image: registry.neec.xyz/neeco/caja-application:latest
    environment:
      CAJA_PORT: 9000
      CAJA_DATABASE_HOST: caja-database
      CAJA_DATABASE_USER:
      CAJA_DATABASE_PASSWORD:
      CAJA_S3_ACCESSKEY:
      CAJA_S3_SECRETKEY:
      CAJA_S3_BUCKETNAME:
      CAJA_SECRET_KEY_BASE:
      CUENTA_URL: http://cuenta-application:4000/
      CADENA_URL: http://cadena-application:3000/
    depends_on:
      - caja-database
    networks:
      - caja
      - caja-cadena
      - caja-cuenta
      - kong-caja

  # Cuenta
  cuenta-database:
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: cuenta_prod
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: $CUENTA_DATABASE_USER
      MYSQL_PASSWORD: $CUENTA_DATABASE_PASSWORD
    volumes:
      - cuenta:/var/lib/mysql
    networks:
      - cuenta
      - dios-cuenta
  cuenta-application:
    image: registry.neec.xyz/neeco/cuenta-application:latest
    environment:
      CUENTA_PORT: 4000
      CUENTA_DATABASE_HOST: cuenta-database
      CUENTA_DATABASE_USER:
      CUENTA_DATABASE_PASSWORD:
      IMAGEN_URL: http://imagen-application:8000/
      KONG_URL: http://kong-application:8001/
      OLVIDO_URL: http://olvido-application:8080/
      STATIC_IMAGE_URL:
    depends_on:
      - cuenta-database
    networks:
      - cuenta
      - cuenta-imagen
      - cuenta-olvido
      - aldea-cuenta
      - cadena-cuenta
      - caja-cuenta
      - kong-cuenta

  # Dios
  dios-database:
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: dios_production
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: $DIOS_DATABASE_USER
      MYSQL_PASSWORD: $DIOS_DATABASE_PASSWORD
    volumes:
      - dios:/var/lib/mysql
    networks:
      - dios
  dios-application:
    image: registry.neec.xyz/neeco/dios-application:latest
    environment:
      RAILS_LOG_TO_STDOUT: 'true'
      DIOS_PORT: 3000
      DIOS_DATABASE_HOST: dios-database
      DIOS_DATABASE_USER:
      DIOS_DATABASE_PASSWORD:
      DIOS_SECRET_KEY_BASE:
      KONG_URL: http://kong-application:8001/
      IMAGEN_URL: http://imagen-application:8000/
      CAJA_DATABASE_HOST: caja-database
      CAJA_DATABASE_USER:
      CAJA_DATABASE_PASSWORD:
      CUENTA_DATABASE_HOST: cuenta-database
      CUENTA_DATABASE_USER:
      CUENTA_DATABASE_PASSWORD:
      ALDEA_DATABASE_HOST: aldea-database
      ALDEA_DATABASE_USER:
      ALDEA_DATABASE_PASSWORD:
    depends_on:
      - dios-database
    networks:
      - dios
      - puerta-dios
      - dios-aldea
      - dios-caja
      - dios-cuenta
      - dios-imagen
      - dios-kong

  # Imagen
  imagen-application:
    image: registry.neec.xyz/neeco/imagen-application:latest
    environment:
      IMAGEN_PORT: 8000
      IMAGEN_WORKERS: 5
    volumes:
      - images:/srv/imagen/images/
    networks:
      - aldea-imagen
      - cadena-imagen
      - cuenta-imagen
      - dios-imagen

  # Kong
  kong-database:
    image: postgres:9.4
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    volumes:
      - kong:/var/lib/postgresql/data
    networks:
      - kong
  kong-application:
    image: registry.neec.xyz/neeco/kong-application:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
    depends_on:
      - kong-database
    networks:
      - kong
      - puerta-kong
      - kong-aldea
      - kong-cadena
      - kong-caja
      - kong-cuenta
      - kong-olvido
      - dios-kong

  # Olvido
  olvido-database:
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: olvido_production
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: $OLVIDO_DATABASE_USER
      MYSQL_PASSWORD: $OLVIDO_DATABASE_PASSWORD
    volumes:
      - olvido:/var/lib/mysql
    networks:
      - olvido
  olvido-application:
    image: registry.neec.xyz/neeco/olvido-application:latest
    environment:
      OLVIDO_PORT: 8080
      OLVIDO_DATABASE_HOST: olvido-database
      OLVIDO_DATABASE_USER:
      OLVIDO_DATABASE_PASSWORD:
      OLVIDO_APP_KEY:
      OLVIDO_HASH_KEY:
      OLVIDO_CIPHER_KEY:
    depends_on:
      - olvido-database
    networks:
      - olvido
      - kong-olvido
      - cuenta-olvido

  # Puerta
  puerta-application:
    image: registry.neec.xyz/neeco/puerta-application:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.htpasswd:/etc/h2o/.htpasswd:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - images:/public/images/:ro
    networks:
      - puerta
      - puerta-web
      - puerta-kong
      - puerta-dios

  # Web
  web-application:
    image: nginx:1.10.2-alpine
    networks:
      - puerta-web

volumes:
  aldea:
    external:
      name: neeco_aldea
  cadena:
    external:
      name: neeco_cadena
  caja:
    external:
      name: neeco_caja
  cuenta:
    external:
      name: neeco_cuenta
  dios:
    external:
      name: neeco_dios
  kong:
    external:
      name: neeco_kong
  olvido:
    external:
      name: neeco_olvido
  images:
    external:
      name: neeco_images

networks:
  aldea:
    external:
      name: neeco_aldea
  cuenta:
    external:
      name: neeco_cuenta
  cadena:
    external:
      name: neeco_cadena
  caja:
    external:
      name: neeco_caja
  dios:
    external:
      name: neeco_dios
  kong:
    external:
      name: neeco_kong
  olvido:
    external:
      name: neeco_olvido
  puerta:
    external:
      name: neeco_puerta
  puerta-web:
    external:
      name: neeco_puerta-web
  puerta-kong:
    external:
      name: neeco_puerta-kong
  puerta-dios:
    external:
      name: neeco_puerta-dios
  kong-aldea:
    external:
      name: neeco_kong-aldea
  kong-cadena:
    external:
      name: neeco_kong-cadena
  kong-caja:
    external:
      name: neeco_kong-caja
  kong-cuenta:
    external:
      name: neeco_kong-cuenta
  kong-olvido:
    external:
      name: neeco_kong-olvido
  dios-aldea:
    external:
      name: neeco_dios-aldea
  dios-caja:
    external:
      name: neeco_dios-caja
  dios-cuenta:
    external:
      name: neeco_dios-cuenta
  dios-imagen:
    external:
      name: neeco_dios-imagen
  dios-kong:
    external:
      name: neeco_dios-kong
  aldea-imagen:
    external:
      name: neeco_aldea-imagen
  cadena-imagen:
    external:
      name: neeco_cadena-imagen
  cuenta-imagen:
    external:
      name: neeco_cuenta-imagen
  cuenta-olvido:
    external:
      name: neeco_cuenta-olvido
  aldea-cuenta:
    external:
      name: neeco_aldea-cuenta
  cadena-cuenta:
    external:
      name: neeco_cadena-cuenta
  caja-cadena:
    external:
      name: neeco_caja-cadena
  caja-cuenta:
    external:
      name: neeco_caja-cuenta
