version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - /var/lib/postgresql/data
  database:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    ports:
      - "5432:5432"
  application:
    image: mashape/kong
    environment:
      - DATABASE=postgres
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "7946:7946"
      - "7946:7946/udp"
